const fs = require('fs'); 
const lines = [ 
'import React, { useEffect } from \u0022react\u0022;', 
'import { Navigate, Outlet, useLocation, useNavigate } from \u0022react-router-dom\u0022;', 
'import { Loader2 } from \u0022lucide-react\u0022;', 
'import { useAuth } from \u0022../context/AuthContext\u0022;', 
'', 
'const ROLE_PATHS = {', 
'    patient: \u0022/dashboard/patient\u0022,', 
'    hospital: \u0022/dashboard/hospital\u0022,', 
'    doctor: \u0022/dashboard/doctor\u0022', 
'};', 
'', 
'export const DashboardGate = ({ children }) =
'    const { user, loading } = useAuth();', 
'    if (loading) {', 
'        return (', 
'            <div className=\u0022flex h-screen items-center justify-center\u0022>', 
'                <Loader2 className=\u0022animate-spin text-p-600\u0022 size={32} />', 
'            </div>', 
'        );', 
'    }', 
'    if (!user) {', 
'        return <Navigate to=\u0022/login/patient\u0022 replace />;', 
'    return children ? children : <Outlet />;', 
'};', 
'', 
'export const RoleRedirect = () =
'    const { user, loading } = useAuth();', 
'    const navigate = useNavigate();', 
'    const location = useLocation();', 
'', 
'    useEffect(() =
'        if (!location.pathname.startsWith(\u0022/dashboard\u0022)) return;', 
'        const target = ROLE_PATHS[user.role];', 
'        if (!target) {', 
'            navigate(\u0022/\u0022, { replace: true });', 
'            return;', 
'        }', 
'        if (location.pathname.startsWith(target)) return;', 
'        if (location.pathname !== \u0022/dashboard\u0022 && location.pathname !== \u0022/dashboard/\u0022) {', 
'            navigate(target, { replace: true });', 
'            return;', 
'        }', 
'        navigate(target, { replace: true });', 
'    }, [loading, location.pathname, navigate, user]);', 
'', 
'    return null;', 
'};', 
'', 
'export const RoleGuard = ({ allowedRole, children }) =
'    const { user, loading } = useAuth();', 
'    if (loading) return null;', 
'    if (!user) return <Navigate to=\u0022/\u0022 replace />;', 
'    const roles = Array.isArray(allowedRole) ? allowedRole : [allowedRole];', 
'    if (!roles.includes(user.role)) {', 
'        return <Navigate to=\u0022/\u0022 replace />;', 
'    }', 
'    return children;', 
'};', 
]; 
const content = lines.map(line =, String.fromCharCode(34))).join('\\n'); 
fs.writeFileSync('src/components/RoleRouter.jsx', content, 'utf8'); 
